### ISSUE TITLE
2 issuesplus 2PM  ver 1.6.0: fields grayed out + not discovered anymore after delete (attempt to reproduce)

### ISSUE THREAD

**Issue by skloos68** [bieniu/ha-shellies-discovery-gen2#103]
**Describe the bug**
After installing Release 1.6.0 (fixing issues 100/101) 2 new issues apprear:

- Installed the new python script version
- restarted HA
  - The device is now recognized but,
          - the relays do not show up as controls
          
  (1)   - all device specific sensors show up but grayed out
         - my test device is set up as switch (profile) and next to relay's I see all Cover controls as well grayed out.
         - Power and energy sensors are also grayed-out
         - expected behavior: only Switch specific sensors would be visible

         - all generic sensors, (Wfi, update, etc seem fine)

To reproduce and make sure I was not too hasty; I removed the device from HA restarted HA (also restarted the docker instance separately as well as 2nd attempt)

(2)    - after waiting and later a manual triggering of Gen2 Announce automation, the device is not recognized anymore/again

Since after trying to reproduce the device did not show up anymore, I do not have screenshots. Sorry.

**Expected behavior**
Device is discovered and added with full functionality to HA

**Versions:**
Home Assistant: 2022.10.0 ( but also previous public version)
Shellies Discovery GEN2: Release 1.6.0
Shelly device firmware: 0.11.2
Shellies Discovery GEN2 automation:

**Shellies Discovery GEN2 automation:**
alias: Shellies Announce Gen2
trigger:

platform: homeassistant
event: start
action:
repeat:
for_each: "{{ device_ids }}"
sequence:
- service: mqtt.publish
data:
topic: "{{ repeat.item }}/rpc"
payload: "{{ device_info_payload }}"
variables:
device_info_payload: >-
{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} |
to_json }}
device_ids:
wss18
wss16
- shellyplus2pm-441793ad2fac (device that is powered and active)
alias: Shellies Discovery Gen2
trigger:

platform: mqtt
topic: shellies_discovery/rpc
action:
service: python_script.shellies_discovery_gen2
data:
id: "{{ trigger.payload_json.src }}"
device_config: "{{ trigger.payload_json.result }}"
mode: queued
max: 999

**Debug log:**
[ha.log](https://github.com/bieniu/ha-shellies-discovery-gen2/files/9748469/ha.log)

**Comment by bieniu** [comment]
Please provide one problem per issue and fill up the form.

**Comment by skloos68** [comment]
Thank you Bieniui, you are absolutely correct it works like charm and apologies that I did not spot the needed update in HA. 
Thanks for picking this up so fast.
