### ISSUE TITLE
Requiers HA 2022.11 -> but its installed

### ISSUE THREAD

**Issue by clipse2004** [bieniu/ha-shellies-discovery-gen2#109]
**Describe the bug**
Hi,
I have a problem to install 2.0. 
I use the latest version 2022.11 b4, yet the but wants me to install 2022.11?!  

**Expected behavior**

**Versions:**
 - Home Assistant:  2022.11b4
 - Shellies Discovery GEN2: 1.6.0
 - Shelly device firmware:  0.11.4 (newest)

**Shellies Discovery GEN2 automation:**

```yaml

```

**Debug log:**

```txt

```

**Comment by bieniu** [comment]
2022.11b4 != 2021.11.0

**Comment by clipse2004** [comment]
Then please explain to me why it does not work? 
See photos


![71F10B30-912F-46A3-82AC-7F43A6183CC8](https://user-images.githubusercontent.com/47680803/199128406-00805827-dded-4f76-afd6-dbfad5be3c2e.jpeg)
![65F60B47-6753-4AED-954A-B0C529EC3058](https://user-images.githubusercontent.com/47680803/199128414-d388f2fc-0e9d-49bd-8db8-2e03238878ae.jpeg)

**Comment by bieniu** [comment]
Do you have installed version 2022.11.0?

**Comment by clipse2004** [comment]
You See on the picture above, HA 2022.11b4 is installed

**Comment by cscoppafox** [comment]
I'm curious, now that support for the gen 2 battery powered devices is cooked into 2022.11 (I've been on all the betas, it works except for getting confused between C. and F. after restarting HA, but it always recovers) ... what's the benefit of still running your scripts?   

Thanks for creating them, I was using them before the 2022.11 beta came out and they do work great!

**Comment by bieniu** [comment]
> HA 2022.11b4 is installed

Yes, you right, 2022.11.0b4, not 2022.11.0. After installing 2022.11.0 you will be able to update the script in HACS.

**Comment by bieniu** [comment]
@cscoppafox Please do not spam the thread. If you have questions you can open an issue or tag me on community thread. By the way, on the Shellies Discovery thread on community you should find an answer for the question.
