### ISSUE TITLE
Shelly Pro 3em - request to include EMData (energy, energy returned, total energy)

### ISSUE THREAD

**Issue by OliHall** [bieniu/ha-shellies-discovery-gen2#146]
Hi,

Thank you for your great work on the Shellies Discovery Script. I installed the latest version of the script to test yesterday's commit where you added support for the new Shelly Pro 3EM.

I have tested it with my Shelly Pro 3EM device and I can see the instant power metrics including: 'active power', 'apparent power', 'current', 'power factor' and 'voltage' all appear to work well. Thank you!

I am also hoping when you have time, please can you try and add the cumulative energy data from the EMData component which stores 'energy', 'energy returned', 'total energy', natively in Wm (wattminutes), but preferably converted into kWh.

It would be great if you could add the data from the EMData component so that kWh consumption can be used from the Shelly registers without having to integrate the Watts over time which is less accurate.

Many thanks,
Oli.

**Comment by OliHall** [comment]
Ok, thank you for the quick response. Is this why the EMData component is empty in the message payloads below?

> \"emdata:0\":{\"id\":0},

**Comment by bieniu** [comment]
You have to use `EMData.GetData` method https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/EMData#emdatagetdata-example
Example: `{"id":1, "src": "test", "method": "EMData.GetData", "params": {"id": 0, "ts": 1656356400}}`

To implement these values in the script, the device must push them.

**Comment by OliHall** [comment]
Thank you for your help. I am also following the other issue [re.](https://github.com/home-assistant/core/issues/85941) affecting the core Shelly integration as well. I hope Shelly add this info to the push messaging soon.

**Comment by bieniu** [comment]
Closed via https://github.com/bieniu/ha-shellies-discovery-gen2/pull/150
