### ISSUE TITLE
`script_prefix` argument not working properly

### ISSUE THREAD

**Issue by LordShadowen** [bieniu/ha-shellies-discovery-gen2#157]
**Describe the bug**

When using the script_prefix parameter, not everything works as expected:

1) This gets published on the topic named after the Device ID, created on *root*, instead of being under the prefix:
`{"id": 1, "src": shellies/shelies_discovery_script, "method": "Script.SetConfig", "params": {"id": 1, "config": {"enable": true}}}`

2) The script doesn't get created on the device

3) There is no topic with the name shellies_discovery_script created anywhere

4) Certain entities, like Firmware always stay in the "Unknown" state

A workaround that seems to solve this is to change line 1832 like so:
`topic = encode_config_topic(f"{script_prefix}/{device_id}/rpc")`

**Expected behavior**

All the topics that normally get created on the root should be created under `script_prefix` and entities should work the same as if the parameter was not used

**Versions:**
 - Home Assistant: 
 - Shellies Discovery GEN2: 
 - Shelly device firmware: 

**Shellies Discovery GEN2 automation:**
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload:  "{{ {'id': 1, 'src':'shelliesg2/shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids:  # enter the list of device IDs (MQTT prefixes) here
      - shelliesg2/shellyplus2pm-blabla
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
  - platform: mqtt
    topic: shelliesg2/shellies_discovery/rpc
  action:
  - service: python_script.shellies_discovery_gen2
    data:
      id: "{{ trigger.payload_json.src }}"
      device_config: "{{ trigger.payload_json.result }}"
      script_prefix: "shelliesg2"
      qos: 2

```yaml

```

**Debug log:**
[python_script.log](https://github.com/bieniu/ha-shellies-discovery-gen2/files/10668243/python_script.log)

```txt

```

**Comment by LordShadowen** [comment]
Works great! 👍 
But there is still one issue - not sure if it's a bug yet: when a switch on the device turns on or off, a new topic gets created on the root, with the name "home-assistant/rpc"
The payload looks like this:
`{"id":1,"src":"shellyplus2pm-441793ce1994","dst":"home-assistant","result":{"was_on":true}}`

It seems to be the last state before the change. But it doesn't even identify which relay triggered it, just the device ID.
What is the purpose of this? Is it needed? Does it have to be on the root? Can it be changed?

**Comment by bieniu** [comment]
This is a confirmation of the status change from the device. Home Assistant is the source of this change (causes it), so the answer is published to `home-assistant` topic.

**Comment by LordShadowen** [comment]
I see it on the python script now, thanks.
Ok, so... does HA actually need/use this info? 
I've tweaked line 68 to this:
`HOME_ASSISTANT = "shelliesg2/home-assistant"`
Seems to work just as well as before, and now the topic is again neatly under shelliesg2. 

Any downsides? 
Perhaps it would make sense to apply `script_prefix` to this value as well to achieve the original goal (nothing created on root directly)

**Comment by bieniu** [comment]
If I remember correctly we don't use those responses, I need to check this. If not I will add `script_prefix` to this topic.
