### ISSUE TITLE
Manually specify the domain

### ISSUE THREAD

**Issue by LordShadowen** [bieniu/ha-shellies-discovery-gen2#163]
**Is your feature request related to a problem? Please describe.**
The Gen2 method to determine the domain of the relays (i.e. light vs switch) seems to be related to what's specified in Appliance Type. As mentioned in the instructions, this is broken in firmware 0.13.
Not sure how it used to be in firmware 0.12, but in 0.13 it looks like it's **badly** broken:
- on a Shelly Plus 1 PM, it always reports it as a light, no matter the selection on the UI
- on a Shelly Plus 2 PM, it always reports it as a switch, no matter the selection on the UI
- the field ui_data where this information is provided in the MQTT payload does not seem to be associated to the specific relay, but rather to the device as whole. This means that on a Shelly Plus 2 PM, it would be impossible to configure one relay as a light and another as a switch...

**Describe the solution you'd like**
Since it seems we can't rely on this info any time soon, why not allow the manual specification of the domain like in Gen1? 
We already have to specify the device_id of each one, since there is no auto-discovery - it would be easy to specify next to each one the desired domain.

**Additional context**
This is not as nice as getting this info automatically from the device, but even if the firmware issues get sorted out in the future, this feature could still be useful to override the domain anyway. In the meantime, we would have a working solution

**Comment by bieniu** [comment]
Sooner or later Shelly will fix this bug so IMO it doesn’t make sense is to implement a new feature that won’t be needed in the future. If you want to speed things up you can ask Shelly support for a fix.

BTW currently, you can use SwitchToX helper to change the switch to the light platform.

**Comment by LordShadowen** [comment]
Ok - ticket submitted with Shelly Support :)

Also, SwitchToX could be used to turn a Switch into a Light, but not a Light into a Switch, and that's what is happening with a Shelly Plus 1 PM (it's **always** a light)

**Comment by bieniu** [comment]
You can reset old consumption type by rest API.

**Comment by LordShadowen** [comment]
I don't understand what you mean

**Comment by bieniu** [comment]
You can use `http://device_ip/rpc/Shelly.SetConfig` service to change `consumption_types`.

**Comment by bieniu** [comment]
https://github.com/home-assistant/core/issues/84815#issuecomment-1431577597

**Comment by LordShadowen** [comment]
I got a reply from Shelly about this - it seems we are looking in the wrong place...

https://github.com/home-assistant/core/issues/84815#issuecomment-1440084207

**Comment by bieniu** [comment]
No, they're trying to pretend the problem isn't on their end, and it definitely is.
