### ISSUE TITLE
Discovery script don't recognize services

### ISSUE THREAD

**Issue by cryptolukas** [bieniu/ha-shellies-discovery-gen2#228]
**Describe the bug**
Add the new shelly gen2 script and a new i4 device isn't recognized

**Expected behavior**
Gen2 devices should be recognized from HA

**Versions:**
- Home Assistant: 2023.6.2
 - Shellies Discovery GEN2: 2.14.0
 - Shelly device firmware: 20230308-091236/0.14.1-g22a4cb7
 
**Shellies Discovery GEN2 automation:**

```yaml
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload: "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids: # enter the list of device IDs (MQTT prefixes) here
      - 'i4Wohnzimmer/shellyplusi4-b8d61a8a4494'
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
    - platform: mqtt
      topic: shellies_discovery/rpc
  action:
    - service: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
```

**Debug log:**

```txt

$ tail -f config/home-assistant.log
2023-06-25 00:01:06.426 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'dict object' has no attribute 'payload_json' when rendering '{{ trigger.payload_json.src }}'
2023-06-25 00:01:21.059 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'
2023-06-25 00:01:21.087 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Error while executing automation automation.shellies_discovery_gen2: Error rendering data template: UndefinedError: 'dict object' has no attribute 'payload_json'
```

**Comment by cryptolukas** [comment]
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/6566612/e32733fd-adf5-435f-a151-9b403ce107dc)

**Comment by bieniu** [comment]
Wrong configuration
![obraz](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/478555/cd732541-7d67-4681-ba73-7d5b4ce0f1da)

**Comment by cryptolukas** [comment]
Change it to the MQTT prefix and format it as string. The device appear now.
Sadly the sensors are not usable.
Is there something I missed?

![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/6566612/8eb7ed87-8527-4c37-a03a-fec0bdde0616)

**Comment by bieniu** [comment]
> Is there something I missed?

If the inputs are configured as buttons you have to use device automation triggers.
Click here
![obraz](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/478555/82a449f1-4cc9-4fa6-bf54-dec573def989)

**Comment by cryptolukas** [comment]
The input configured as switches and not buttons :(
What could be the issue?

![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/6566612/5c61ebe4-d586-4bdb-8cae-499c5cc7155b)
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/6566612/841fb431-4702-47d8-838f-62bdba7c92a1)

**Comment by bieniu** [comment]
If I remember correctly you have to use the physical switches to make the entities available.

**Comment by cryptolukas** [comment]
Pressed the physical switches and there is no update inside of Home Assistant.
The logbook don't recognize that the button were pressed.
If I click the restart button it is working.

I checked the mqtt messages directly with MQTT explorerer. The MQTT messages arrive mosquitto.
Home Assistant don't get the updates.
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/6566612/0343ada1-4629-4cec-9016-3744a4a012f9)

**Comment by bieniu** [comment]
I assume that you have manually enabled input entities (they are disabled by default).

**Comment by cryptolukas** [comment]
Can you tell me where I can check the status of it?
Don't know how verify that input entities are disabled.

**Comment by bieniu** [comment]
![obraz](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/478555/f6887c79-844f-4199-acc3-1fee569d448f)
![obraz](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/478555/36c89605-5683-498d-88ba-929220868dbf)

**Comment by cryptolukas** [comment]
Thank you!!!
You made my sunday and my living room :)

The manually changing was helping!

Have a nice sunday :)
