### ISSUE TITLE
Support for Shelly Pro 3EM Switch Add-On

### ISSUE THREAD

**Issue by zylxpl** [bieniu/ha-shellies-discovery-gen2#333]
**Is your feature request related to a problem? Please describe.**

  No support for Shelly Pro 3EM Switch Add-On

**Describe the solution you'd like**

  Be able to use Shelly Pro 3EM Switch Add-On.

**Comment by bieniu** [comment]
I need responses for:
- `Shelly.GetConfig`
- `Shelly.GetStatus`

**Comment by zylxpl** [comment]
`{
  "ble": {},
  "cloud": {"connected": true},
  "em:0": {
    "id": 0,
    "a_current": 1.576,
    "a_voltage": 243.4,
    "a_act_power": 266.5,
    "a_aprt_power": 383.4,
    "a_pf": 0.76,
    "a_freq": 50.0,
    "b_current": 0.412,
    "b_voltage": 243.9,
    "b_act_power": 1.1,
    "b_aprt_power": 100.5,
    "b_pf": 0.50,
    "b_freq": 50.0,
    "c_current": 1.687,
    "c_voltage": 244.5,
    "c_act_power": 213.3,
    "c_aprt_power": 412.1,
    "c_pf": 0.68,
    "c_freq": 50.0,
    "n_current": null,
    "total_current": 3.675,
    "total_act_power": 480.924,
    "total_aprt_power": 896.039,
    "user_calibrated_phase": []
  },
  "emdata:0": {
    "id": 0,
    "a_total_act_energy": 819087.50,
    "a_total_act_ret_energy": 0.00,
    "b_total_act_energy": 90579.48,
    "b_total_act_ret_energy": 35.19,
    "c_total_act_energy": 652717.23,
    "c_total_act_ret_energy": 0.00,
    "total_act": 1562384.20,
    "total_act_ret": 35.19
  },
  "eth": {"ip": null},
  "modbus": {},
  "mqtt": {"connected": true},
  "script:1": {
    "id": 1,
    "running": true,
    "mem_used": 434,
    "mem_peak": 6608,
    "mem_free": 24766
  },
  "switch:100": {
    "id": 100,
    "source": "user_button",
    "output": false,
    "temperature": {"tC": 33.0, "tF": 91.3}
  },
  "sys": {
    "mac": "XX:XX:XX:XX:XX:XX",
    "restart_required": false,
    "time": "16:40",
    "unixtime": 1703173206,
    "uptime": 16000,
    "ram_size": 240996,
    "ram_free": 97480,
    "fs_size": 524288,
    "fs_free": 180224,
    "cfg_rev": 39,
    "kvs_rev": 0,
    "schedule_rev": 0,
    "webhook_rev": 0,
    "available_updates": {},
    "reset_reason": 3
  },
  "temperature:0": {
    "id": 0,
    "tC": 49.7,
    "tF": 121.5
  },
  "wifi": {
    "sta_ip": "XXX.XXX.XXX.XXX",
    "status": "got ip",
    "ssid": "NETWORK_NAME",
    "rssi": -67
  },
  "ws": {"connected": false}
}
`

**Comment by bieniu** [comment]
Please use this script file and test the solution https://github.com/bieniu/ha-shellies-discovery-gen2/blob/04740292fc05625cba6ee3ffb0f9b3214bc666ae/python_scripts/shellies_discovery_gen2.py

**Comment by zylxpl** [comment]
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/13242378/5a597426-9b04-4109-a0c6-404cf1dc5263)
Looks like everything is working.
