### ISSUE TITLE
Shellies Announce Gen2: Repeat 'for_each' must be a list of items in Shellies Announce Gen2

### ISSUE THREAD

**Issue by ltksolutions** [bieniu/ha-shellies-discovery-gen2#344]
**  Logger: homeassistant.components.automation.shellies_announce_gen2
Source: helpers/script.py:1792
Integration: Automatizácia (documentation, issues)
First occurred: 00:23:44 (1 occurrences)
Last logged: 00:23:44

Shellies Announce Gen2: Repeat 'for_each' must be a list of items in Shellies Announce Gen2, got: None**

**Expected behavior**

**Versions:**
 - Home Assistant: 2024.1.2
 - Shellies Discovery GEN2: 2.25.0
 - Shelly device firmware: latest

**Shellies Discovery GEN2 automation:**

```yaml

```

**Shelly device MQTT settings:**

**Debug log:**

```txt

```

**Comment by bieniu** [comment]
Your Shellies announce automation is invalid and you have the exact information in the log what is wrong.

**Comment by ltksolutions** [comment]
configuration fixed, all work super, thanks ...
