### ISSUE TITLE
HACS update sensor becomes unavailable after restart of homeassistant

### ISSUE THREAD

**Issue by h3llrais3r** [bieniu/ha-shellies-discovery-gen2#349]
**Describe the bug**
Running version 2.23.0.
A sensor is also created to notify when an update of the script is found.
The sensor works, but from the moment I restart homeassistant, the sensor beomes unavailable and doesn't work anymore.

![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/1945295/d8149d68-9958-455c-9123-00fd4199f0b8)

**Expected behavior**
The update sensor also works after restart.

**Versions:**
 - Home Assistant: 2024.1.2
 - Shellies Discovery GEN2: 2.23.0
 - Shelly device firmware: N/A

**Shellies Discovery GEN2 automation:**
N/A

**Shelly device MQTT settings:**
N/A

**Debug log:**
N/A

**Comment by h3llrais3r** [comment]
I've just updated to the latest version 2.26.0 and for now it seems to work after a restart.
I'll keep an eye on it in the coming days if it's still happening.

**Comment by bieniu** [comment]
This is a HACS issue.

**Comment by h3llrais3r** [comment]
Ok, thanks for letting me know. Wasn't sure if it was related to HACS or not, as I don't have it for other HACS update sensors.

**Comment by bieniu** [comment]
You can easily check that, if the update entity is `unavailable`, you will not see the `python scripts` category in HACS at all.

**Comment by h3llrais3r** [comment]
Yes, that's what I was experiencing... I couldn't find any `python_scripts` integration in HACS at all.
