### ISSUE TITLE
Model PlugS is not supported

### ISSUE THREAD

**Issue by Janorei** [bieniu/ha-shellies-discovery-gen2#387]
**Describe the bug**

  File "shellies_discovery_gen2.py", line 3121, in <module>
ValueError: model plusplugs is not supported, please open an issue here https://github.com/bieniu/ha-shellies-discovery-gen2/issues
2024-03-16 18:54:23.108 ERROR (SyncWorker_2) [homeassistant.components.python_script.shellies_discovery_gen2.py] Error executing script: model plusplugs is not supported, please open an issue here https://github.com/bieniu/ha-shellies-discovery-gen2/issues
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 269, in execute
    exec(compiled.code, restricted_globals)  # noqa: S102
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Expected behavior**
  Plug S Model should be supported

**Versions:**
 - Home Assistant: 
Core 2024.3.0
Supervisor 2024.03.0
Operating System 12.0
Frontend 20240306.0
 - Shellies Discovery GEN2: Newest
 - Shelly device firmware:  Newest

**Shellies Discovery GEN2 automation:**

```yaml

```

**Shelly device MQTT settings:**

**Debug log:**

```txt

```

**Comment by bieniu** [comment]
Plus Plug S is supported for ages. Please provide more information or the issue will be closed.

![obraz](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/478555/2384f9d0-438b-4951-ab17-d1f170b36a74)

**Comment by Janorei** [comment]
Ich habe das selber fixen können im Python Script, der Shelly hat folgende device Info:

{
  "web_id": "240213111718-ce341dc8-HEAD",
  "deviceInfo": {
    "name": null,
    "id": "plusplugs-e465b847b9a4",
    "mac": "E465B847B9A4",
    "slot": 1,
    "key": "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDIwMTUyNTMsIm1hYyI6IkU0NjVCODQ3QjlBNCIsIm0iOiJTTlBMLTAwMTEyRVUiLCJiIjoiMjM0My1Ccm9hZHdlbGxDdWNvIiwiZnAiOiIwNzYzZGRhMiJ9.KyPRGx-x1_4OKZniZX4V7aIhpQnAi_QMZQrFiRyi9gxEO8CPFxhjMhCSxLqH7M7ebJ9BuS6N_JB-4T6Qumz763RGRYqHFrpM4wDxZBaC2P1gKFmB-GM8oIiMoMoQl9fp",
    "batch": "2343-BroadwellCuco",
    "fw_sbits": "04",
    "model": "SNPL-00112EU",
    "gen": 2,
    "fw_id": "20240228-070935/1.2.3-gbd3eceb",
    "ver": "1.2.3",
    "app": "PlusPlugS",
    "auth_en": false,
    "auth_domain": null
  },

und nicht wie im Script:

 "id": "shellyplusplugs-e465b847b9a4",

**Comment by bieniu** [comment]
The official language here is English. Please translate your comments. Thanks.

**Comment by bieniu** [comment]
> "id": "plusplugs-xxxxxx47b9a4",

Your device ID is wrong, should be `shellyplusplugs-xxxxxx47b9a4`. You need to ask Shelly support why the ID is wrong.

**Comment by Janorei** [comment]
> > "id": "plusplugs-xxxxxx47b9a4",
> 
> Your device ID is wrong, should be `shellyplusplugs-xxxxxx47b9a4`. You need to ask Shelly support why the ID is wrong.
I recognized that, and fixed in in my locale Python Script. Now IT works.

**Comment by Janorei** [comment]
I recognized that and have fixed  IT in my lokal Python Script. Now IT works well.

**Comment by bieniu** [comment]
The fact that the ID is incorrect is very suspicious, you should clarify this with Shelly support.
