### ISSUE TITLE
Home assistant generating many errors

### ISSUE THREAD

**Issue by inch1957** [bieniu/ha-shellies-discovery-gen2#392]
**Describe the bug**

**Expected behavior**

**Versions:**
 - Home Assistant: 
![HA-version](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/74451356/adb386d3-6a32-4130-9d22-0d4f458c94cc)

 - Shellies Discovery GEN2: 
 - 
![HA-gen2-ver](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/74451356/17d29699-72b4-4c01-a6db-d5298110e480)

 - Shelly device firmware:
 - 
![HA-device-fw](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/74451356/88a02628-5c64-4f05-bedc-75a3e2aedea7)
 

**Shellies Discovery GEN2 automation:**
<!--
  Please provide Shellies Discovery automation here.

[shelly_mq_setup.txt](https://github.com/bieniu/ha-shellies-discovery-gen2/files/14733294/shelly_mq_setup.txt)

```


**Shelly device MQTT settings:**
<!--
![HA-device-mqtt](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/74451356/d42d31dd-9078-4d8b-8ae7-5766d34ef795)

  Please provide a screenshot of the Settings -> MQTT section from the device's WebUI.
-->


**Debug log:**
<!--
  Please provide a log file for the following logger configuration:
  logger:
    default: error
    logs:
      homeassistant.components.python_script: debug
      homeassistant.components.automation: info
      homeassistant.components.mqtt.discovery: info
-->
[HA-error-log.txt](https://github.com/bieniu/ha-shellies-discovery-gen2/files/14733277/HA-error-log.txt)

```txt

```

**Comment by bieniu** [comment]
There are two scripts running on your device, one comes from Shellies Discovery, I would like to see the code of the second one because I suspect it is responsible for the errors in the log.

**Comment by inch1957** [comment]
Hello, thanks for getting back so fast!
And then also thank you for providing such wonderful interfaces for the
Shelly devices!!!

These attached are the scripts as I have in my home-assistant, please
advise if/what I can provide for further diagnosis...
Charles

**Comment by bieniu** [comment]
> These attached are the scripts as I have in my home-assistant

I don't see any scripts.

**Comment by bieniu** [comment]
Wait, the template `value_json.result.mqtt.connected` is not used in the Shellies Discovery Gen2 2.27.3.
