### ISSUE TITLE
Support for Shelly Blu Gateway

### ISSUE THREAD

**Issue by Spartacus68** [bieniu/ha-shellies-discovery-gen2#395]
**Is your feature request related to a problem? Please describe.**
 no issue
**Describe the solution you'd like**
I would like to add the new Shelly Blu H&T once it is available. In oder to bind thm into the WLAN I would like to use the Blu Gateway

**Additional context**
 The stick is ordered and I can provide you details if you like.

**Comment by bieniu** [comment]
What will be the profit from adding support for a device that can not be controlled and which does not have any sensors?

**Comment by Spartacus68** [comment]
Hi,

I am not really sure, but I guess that the gateway is necessary to add the blu devices to WLAN. Maybe it is transparent and there is a differnt way to connect Shelly BLU H&T to Homeassistant. I woll let you know. amazon will deliveer today the Gateway but for now I do not have any bluetooth device.

**Comment by bieniu** [comment]
You can use BTHome integration to configure BLU HT/Motion/DW with HA. BLU gateway is not necessary.

**Comment by Spartacus68** [comment]
Hm, I don´t think so. The HA server is far away from any Bluetooth device (more than 50m) . There must be a GW between WLAN and BT in the near environment of the H&T Blu to connect to HA

**Comment by bieniu** [comment]
Every Shelly Gen2+ (non battery-powered) device can work as BT proxy for HA.

**Comment by Spartacus68** [comment]
The device is online. Here is a screenshot from mqtt Explorer
![image](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/121975453/ba05ad3f-09e5-4a16-bc06-819bb2c03ff9)

**Comment by bieniu** [comment]
> The device is online. Here is a screenshot from mqtt Explorer

Nothing interesting here

> The new [BLU H&T ](https://www.shelly.com/de/products/shop/sw10145-1/sw10145-2)are not yet available.

![obraz](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/478555/abc55481-6744-4cdd-80bb-b97bcc0bef32)

**Comment by Spartacus68** [comment]
ok, it seems to be that you have it! But they are not avaiable in the shelly store at the moment.

And,
the question is, how they connect to BTHome, I use all my shellies  Gen2. with mqtt and I do not have a clue how theycan connect without a shelly Gen2 in the near environment. Can BTHome connect to the H&T over the Gen2 Shellies WLAN? And how does the Gateway can connect to the MQTT-Server if it isn´t supported by your integration? Sorry for asking stupid questions but  I belive that the Blu Gw must be attached via mqtt to HA.

Spartacus,

**Comment by bieniu** [comment]
To use BTHome integration, you must have at least one BT proxy configured for HA. It makes no difference whether it is Shelly gen2+ device or ESP32 with ESPHome. You can use Shelly BLU Gateway for this purpose, but the device must be configured via Shelly integration. MQTT does not (and probably will not) support BT event forwarding for HA BT integration.

**Comment by Spartacus68** [comment]
ok, then I'll send the Blu Gateway back and install a Gen2+ in my garden shed! But just to avoid any misunderstandings, the Gen2+ will support BT forwarding in an MQTT integration, right?

**Comment by bieniu** [comment]
No, you need to configure the device with the core Shelly integration to make it a BT proxy. MQTT doesn't support BT event forwarding.

**Comment by Spartacus68** [comment]
Is BT forwarding planned? 
If not, what's the advantage of MQTT integration over Shelly integration if not all features are supported? Sorry, I don't want to start a fundamental discussion, I just want to understand. 

I decided to use mqtt because I also connected Zigbee devices via mqtt, because the Zigbee build-in integration does not support all devices.

**Comment by bieniu** [comment]
> Is BT forwarding planned?

No because it is not possible to implement this without external module that parse BT events.



> If not, what's the advantage of MQTT integration over Shelly integration if not all features are supported?

The main advantage of MQTT is that devices can be in a completely isolated subnet or in the remote location, in the case of core integration this is practically impossible or very difficult. You, as a user, must decide which integration you want to use and why. There is no discussion here about what is better and what is worse. These two ways of integration are simply different.

**Comment by Spartacus68** [comment]
Ah ok, I never thought about this because I am using HA in dedicated subnet :-). 

It's a pity that this is not possible via mqtt! Then, I think, it makes sense to use the BT Gateway with the Shelly integration to have it exclusively for BT purposes and continue to run the Gen2+ via mqtt.
Thanks, that was enlightening and thanks for the discussion.
