### ISSUE TITLE
Shelly Pro 1 second input

### ISSUE THREAD

**Issue by NateLogan** [bieniu/ha-shellies-discovery-gen2#43]
Hello. Is it possible to add sensor for second input for Shelly Pro 1? I can see status of both inputs in "/rpc/Shelly.GetStatus", but Shelly seems to report only one input over MQTT.

Edit: And Home Assistant shows input_0 as unknown... A bug maybe?

**Comment by bieniu** [comment]
> Edit: And Home Assistant shows input_0 as unknown... A bug maybe?

Yes, bug in the Shelly firmware.
