### ISSUE TITLE
adding documentaion

### ISSUE THREAD

**Issue by hros** [bieniu/ha-shellies-discovery-gen2#435]
First, thanks for your great work on automating the MQTT integration of Shelly devices to home-assistant.

After recently replacing a failed Shelly 1PM device, I tried to add the new device to home-assistant
I must have done something wrong, as I can't see the new device in home-assistant, the old (failed) device, which was removed from the Shelly app is still showing in home-assistant (naturally, it is inactive), and what's worse another working 1PM device stopped responding from home-assistant (works from the Shelly app)

I'd appreciate a step-by-step guide on how to add/replace/remove devices

**Comment by bieniu** [comment]
> how to add

Everything you need is here https://github.com/bieniu/ha-shellies-discovery-gen2/blob/master/README.md

> replace

There is no (and will not be) a way to migrate/replace a device configured by the gen1 script to a device configured by the gen2 script.

> remove devices

![obraz](https://github.com/bieniu/ha-shellies-discovery-gen2/assets/478555/cec37f0d-abbb-4450-be0f-f69ec359a8db)

**Comment by hros** [comment]
thanks @bieniu !

Removing the old device worked.

However, the new device (new 1PM) and older 1PM device that used to work (and I somehow ruined it) are still not working in home-assistant

What should the MQTT settings be for 1PM?
<img width="590" alt="image" src="https://github.com/bieniu/ha-shellies-discovery-gen2/assets/2613469/7641bc93-ebce-4165-9b0b-58e367ac96a3">
in the `shellies_announce_gen2` automation, I added the 1PM devices under `device_ids` as "shellies/shellyplus1pm-............"

Is there anything else I need to do to get the devices to appear in home-assistant?
