### ISSUE TITLE
add Support for BT Home devices connected to the Shelly

### ISSUE THREAD

**Issue by Spartacus68** [bieniu/ha-shellies-discovery-gen2#461]
e.g. H&T Sensors
![image](https://github.com/user-attachments/assets/e1f0873d-1f25-4f8c-9cc5-0bec828ec992)

**Comment by bieniu** [comment]
BTHome devices are supported via BTHome integration. I have no plans to implement these devices at this time.

**Comment by Spartacus68** [comment]
BTHome does not support MQTT and cannot be used accress VLANs

**Comment by bieniu** [comment]
BTHome uses Bluetooth so what does this have to do with MQTT and VLANs? 🤔

**Comment by Spartacus68** [comment]
BTHome Gateways are across different locations and different subnets and need to be connected to HA. The GWs are connected via TCP/IP and the BT devices are located near to the GWs

**Comment by bieniu** [comment]
I'm sorry but I still don't see the relation between your network topology and device locations and the need to implement Shelly Bluetooth device support in the Shelly network device script.

IMO all possible use cases can be implemented using BTHome integration.

Bluetooth uses the 2.4 GHz frequency, which penetrates walls quite well. In most cases, you don't need additional BT proxies beyond the controller connected to the HA server.

Besides, if BT device information is not available in the response to Shelly.GetConfig there is absolutely nothing I can do. **Without this, implementation is not possible.**

**Comment by Spartacus68** [comment]
I'm a bit disappointed that you don't see the use case. But then that's just the way it is. Then I will probably have to switch to this [script](https://www.smarthome-forum.eu/user-post-list/96532-spartacus99/) (Blu_to_MQTT).

 It's a pity, because your integration would have been the more convenient solution if the corresponding devices would also be allowed to send the data of the BT devices taught to them.

**Comment by bieniu** [comment]
I will repeat once again, at the moment there is no way to implement this because the script will not receive information about BT devices. Any discussion whether this is a needed or unneeded feature is pointless.
To make the implementation possible, a change to the Shelly API is needed, and they are very reluctant to make such changes.
