### ISSUE TITLE
add support for Shelly 3EM-Pro400

### ISSUE THREAD

**Issue by robotsox** [bieniu/ha-shellies-discovery-gen2#468]
Please add support for the Shelly 3EM-Pro 400.

```
{"name":null,"id":"shellypro3em400-3ce90e6f132c","mac":"3CE90E6F132C","model":"SPEM-003CEBEU400","gen":2,"fw_id":"20230406-080517/0.14.2-pro3em400prod0-g4fc29d5","ver":"0.14.2-pro3em400prod0","app":"Pro3EM","auth_en":false,"auth_domain":null}
```

**Comment by bieniu** [comment]
Please post responses for: 

`http://<DEVICE_IP>/rpc/Shelly.GetConfig`
`http://<DEVICE_IP>/rpc/Shelly.GetStatus`

**Comment by robotsox** [comment]
see attachment
[Shelly.GetConfig.json](https://github.com/user-attachments/files/17096794/Shelly.GetConfig.json)
[Shelly.GetStatus.json](https://github.com/user-attachments/files/17096800/Shelly.GetStatus.json)
