### ISSUE TITLE
Add support for Shelly Plug S G3

### ISSUE THREAD

**Issue by Bo1jo** [bieniu/ha-shellies-discovery-gen2#489]
Please add support for the Shelly Plug S G3.

{"name":null,"id":"shellyplugsg3-543204663204","mac":"543204663204","slot":1,"model":"S3PL-00112EU","gen":3,"fw_id":"20240820-134301/1.2.3-plugsg3prod0-gec79607","ver":"1.2.3-matter22","app":"PlugSG3","auth_en":false,"auth_domain":null,"matter":true}

**Comment by bieniu** [comment]
Please show me the response to:
`http://<device IP address>/rpc/Shelly.GetConfig`
and
`http://<device IP address>/rpc/Shelly.GetStatus`

**Comment by Bo1jo** [comment]
see attachment
[Getstatus.json](https://github.com/user-attachments/files/17451805/Getstatus.json)
[Getconfig.json](https://github.com/user-attachments/files/17451806/Getconfig.json)
