### ISSUE TITLE
Shelly 2PM Cover GoToPosition not working

### ISSUE THREAD

**Issue by lukasvice** [bieniu/ha-shellies-discovery-gen2#51]
**Describe the bug**

Having Shelly 2PM (cover mode) move to a fixed position is not working correctly. The MQTT command does not send the position correctly.
When I took the MQTT payload sent from HA to the Shelly and replaced the position value, and sent it manually, it worked.

Here's the MQTT payload sent from HA:
```json
{"id":1,"src":"shellyplus2pm-XXXXXXXXXXX","method":"Cover.GoToPosition","params":{"id":0,"pos":position}}
````

I tried to modify the script, but unfortunately I couldn't solve the issue :(

**Expected behavior**

Blinds should move to the correct position.

**Versions:**
 - Home Assistant: 2022.3.1
 - Shellies Discovery GEN2: 1.1.4
 - Shelly device firmware: 0.10.0-beta5

**Comment by bieniu** [comment]
Please test the script from this branch https://github.com/bieniu/ha-shellies-discovery-gen2/compare/cover-pos?expand=1

**Comment by lukasvice** [comment]
It works with this version! Thank you very much!
