### ISSUE TITLE
Problems with installation process

### ISSUE THREAD

**Issue by GerhardKreuzer** [bieniu/ha-shellies-discovery-gen2#537]
**Describe the bug**

**Expected behavior**

**Versions:**
 - Home Assistant: 2024.12.2
 - Shellies Discovery GEN2: your newest version
 - Shelly device firmware: 20241007-074728/1.4.99-blugwg3prod2-g689f175

**Shellies Discovery GEN2 automations:**

```yaml

```

**Shelly device MQTT settings:**

**Debug log:**

```txt

```

**Comment by bieniu** [comment]
Please complete the form, otherwise the issue will be closed.

**Comment by GerhardKreuzer** [comment]
Hi,
so this is a strange tool. Typed in my problem and now all text is gone, so here is a test

**Comment by GerhardKreuzer** [comment]
Ok,, Test is ok, so my question again:

I tried to install the script. I followed all the steps, Python Script is running in HA, the hello_world.py sample works, I found the script in HACS, I executed the script and it discovered a Shelly 1PM. Nice, but I need it for my two Shelly TRV BLU via a Shelly BLU Gen 3 Gateway, which also is working.

I tried to run the script a second time, but can't find it in HA.

I restarted HA, no script, no TRV.

Can you please provide a step by step procedure how to setup a Shelly BLU device. If there were more than one available, how can I pick one?

Thanks a lot.

With best regards

Gerhard

**Comment by bieniu** [comment]
There is no special instruction for BLU TRV, BT devices are discovered automatically via BLU Gateway or Shelly Gen3 device. You must provide BLU Gateway ID to the announce automation and restart HA.

**Comment by GerhardKreuzer** [comment]
Ah, ok, that wasn't that clear. Is this automation running once after a start or periodically? Any configuration to do? Exept the ID?

**Comment by GerhardKreuzer** [comment]
Ok, last problem: Where to find the ID of the gen3 Gateway or, if neccessary, where to find the IDs of the TRVs?
Web-interface? Which name?

**Comment by GerhardKreuzer** [comment]
Ok, with the Web interface of the gateway I found a MQTT Id, looks quite similar to the number in the sample.
But now:
![image](https://github.com/user-attachments/assets/0c2e64dd-5b42-4e46-88fc-881cc8b6b155)

So someething happens during the copy and paste ..

**Comment by bieniu** [comment]
The answers to your questions are available within the automation itself.

![image](https://github.com/user-attachments/assets/5446cef9-be10-4d95-9bc2-d64e5a108137)

**Comment by GerhardKreuzer** [comment]
OK, sorry, all new to me.
But:
![image](https://github.com/user-attachments/assets/99d89a91-26e9-46fe-b4bc-057b01cb8ca5)

I run the newest HA version here.

**Comment by bieniu** [comment]
I've updated automations to the new syntax.

**Comment by GerhardKreuzer** [comment]
Thanks,
after starting HA this 'Announce' automation is triggered but the other not.

Where should I see the TRV? I checked everything, no device, no entity. I find nothing with infos about a TRV.
I woked up the TRV by turning the knob, display weents on, before I started HA or run the script manually.
I also entered the debug setup lines.

I don't find anything about a TRV, sorry.

With beest regards

Gerhard

**Comment by bieniu** [comment]
> after starting HA this 'Announce' automation is triggered but the other not.

You can run the announce automation manually and come back to the open post and complete the form, I can’t help you without some diagnostics information.

**Comment by GerhardKreuzer** [comment]
Hi,
I run it manually many timees, but didn't see any effects. Wher to look for results?

I can't get all the requested infos yet, sorry, I am out of office, will add tomorrow, but settings in Shelly device (here Gateway) is as expexted.

Here a trace:
{
  "trace": {
    "last_step": "action/0/repeat/sequence/1",
    "run_id": "e244b3b611acaa4d0371271f4906184f",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2024-12-13T08:27:26.887506+00:00",
      "finish": "2024-12-13T08:27:26.920008+00:00"
    },
    "domain": "automation",
    "item_id": "shellies_announce_gen2",
    "trigger": null,
    "trace": {
      "trigger": [
        {
          "path": "trigger",
          "timestamp": "2024-12-13T08:27:26.888379+00:00",
          "changed_variables": {
            "this": {
              "entity_id": "automation.shellies_announce_gen2",
              "state": "on",
              "attributes": {
                "id": "shellies_announce_gen2",
                "last_triggered": "2024-12-12T22:54:44.259543+00:00",
                "mode": "single",
                "current": 0,
                "friendly_name": "Shellies Announce Gen2"
              },
              "last_changed": "2024-12-12T22:48:53.562555+00:00",
              "last_reported": "2024-12-12T22:54:44.288775+00:00",
              "last_updated": "2024-12-12T22:54:44.288775+00:00",
              "context": {
                "id": "01JEYH9T12Z2BJJ9Q1CCJFSVKG",
                "parent_id": "01JEYH9T109HHXZRZGHCDQ0VCZ",
                "user_id": null
              }
            },
            "trigger": {
              "platform": null
            },
            "get_config_payload": {
              "id": 1,
              "src": "shellies_discovery",
              "method": "Shelly.GetConfig"
            },
            "get_components_payload": {
              "id": 1,
              "src": "shellies_discovery",
              "method": "Shelly.GetComponents",
              "params": {
                "include": [
                  "config"
                ]
              }
            },
            "device_ids": [
              "shellyblugwg3-8cbfeaa8c4b0",
              "shellyblutrv-d6d3fc476828"
            ]
          }
        }
      ],
      "action/0": [
        {
          "path": "action/0",
          "timestamp": "2024-12-13T08:27:26.890556+00:00",
          "changed_variables": {
            "context": {
              "id": "01JEZJ2F96E5HNTQQC00HB6R7Y",
              "parent_id": "01JEZJ2F95851W8ZPX8W998BN4",
              "user_id": null
            }
          }
        }
      ],
      "action/0/repeat/sequence/0": [
        {
          "path": "action/0/repeat/sequence/0",
          "timestamp": "2024-12-13T08:27:26.895453+00:00",
          "changed_variables": {
            "repeat": {
              "first": true,
              "index": 1,
              "last": false,
              "item": "shellyblugwg3-8cbfeaa8c4b0"
            }
          },
          "result": {
            "params": {
              "domain": "mqtt",
              "service": "publish",
              "service_data": {
                "topic": "shellyblugwg3-8cbfeaa8c4b0/rpc",
                "payload": {
                  "id": 1,
                  "src": "shellies_discovery",
                  "method": "Shelly.GetConfig"
                }
              },
              "target": {}
            },
            "running_script": false
          }
        },
        {
          "path": "action/0/repeat/sequence/0",
          "timestamp": "2024-12-13T08:27:26.911489+00:00",
          "changed_variables": {
            "repeat": {
              "first": false,
              "index": 2,
              "last": true,
              "item": "shellyblutrv-d6d3fc476828"
            }
          },
          "result": {
            "params": {
              "domain": "mqtt",
              "service": "publish",
              "service_data": {
                "topic": "shellyblutrv-d6d3fc476828/rpc",
                "payload": {
                  "id": 1,
                  "src": "shellies_discovery",
                  "method": "Shelly.GetConfig"
                }
              },
              "target": {}
            },
            "running_script": false
          }
        }
      ],
      "action/0/repeat/sequence/1": [
        {
          "path": "action/0/repeat/sequence/1",
          "timestamp": "2024-12-13T08:27:26.906164+00:00",
          "result": {
            "params": {
              "domain": "mqtt",
              "service": "publish",
              "service_data": {
                "topic": "shellyblugwg3-8cbfeaa8c4b0/rpc",
                "payload": {
                  "id": 1,
                  "src": "shellies_discovery",
                  "method": "Shelly.GetComponents",
                  "params": {
                    "include": [
                      "config"
                    ]
                  }
                }
              },
              "target": {}
            },
            "running_script": false
          }
        },
        {
          "path": "action/0/repeat/sequence/1",
          "timestamp": "2024-12-13T08:27:26.914228+00:00",
          "result": {
            "params": {
              "domain": "mqtt",
              "service": "publish",
              "service_data": {
                "topic": "shellyblutrv-d6d3fc476828/rpc",
                "payload": {
                  "id": 1,
                  "src": "shellies_discovery",
                  "method": "Shelly.GetComponents",
                  "params": {
                    "include": [
                      "config"
                    ]
                  }
                }
              },
              "target": {}
            },
            "running_script": false
          }
        }
      ]
    },
    "config": {
      "id": "shellies_announce_gen2",
      "alias": "Shellies Announce Gen2",
      "triggers": [
        {
          "trigger": "homeassistant",
          "event": "start"
        }
      ],
      "variables": {
        "get_config_payload": "{{ {'id': 1, 'src': 'shellies_discovery', 'method': 'Shelly.GetConfig'} | to_json }}",
        "get_components_payload": "{{ {'id': 1, 'src': 'shellies_discovery', 'method':'Shelly.GetComponents', 'params': {'include': ['config']}} | to_json }}",
        "device_ids": [
          "shellyblugwg3-8cbfeaa8c4b0",
          "shellyblutrv-d6d3fc476828"
        ]
      },
      "actions": [
        {
          "repeat": {
            "for_each": "{{ device_ids }}",
            "sequence": [
              {
                "action": "mqtt.publish",
                "data": {
                  "topic": "{{ repeat.item }}/rpc",
                  "payload": "{{ get_config_payload }}"
                }
              },
              {
                "action": "mqtt.publish",
                "data": {
                  "topic": "{{ repeat.item }}/rpc",
                  "payload": "{{ get_components_payload }}"
                }
              }
            ]
          }
        }
      ]
    },
    "blueprint_inputs": null,
    "context": {
      "id": "01JEZJ2F96E5HNTQQC00HB6R7Y",
      "parent_id": "01JEZJ2F95851W8ZPX8W998BN4",
      "user_id": null
    }
  },
  "logbookEntries": [
    {
      "name": "Shellies Announce Gen2",
      "message": "triggered",
      "source": null,
      "entity_id": "automation.shellies_announce_gen2",
      "context_id": "01JEZJ2F96E5HNTQQC00HB6R7Y",
      "domain": "automation",
      "when": 1734078446.888635
    }
  ]
}

Whre to get debug informations? I only have a logbook and there is nothing in except 'Script ... started'

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Hi,
I also have an MQTT integration, but here I didn't find a Shelly device, so should I add something here and how?
Enabled the debugging here also.
With best regards
Gerhard

**Comment by GerhardKreuzer** [comment]
Hi, here the screenshot of the shelly MQTT web site, sorry, can't include it into the form above. Tried it, no image appera ..
![image](https://github.com/user-attachments/assets/c1fe77b4-beaa-435e-8a08-718370b83ca2)

Here, no problem.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
OK,
I tried to fill in user und pwd and server IP (wheree HA is running) into the MQTT settings of my Shelly Gen3 Gateway, ((have to learn more about MQTT)). Now some new happens:
![image](https://github.com/user-attachments/assets/b2d24d73-acfb-4779-b114-13fe62d3ea31)
The second script runs now for the first time, but with errors ..

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Ok, intresting:
I download the trace of the script, seecond linee in red means 'script not found', but I see it in the list of automations and also in the automations.yaml.
Inside the race I found lot of valid information from the Gateway and some of my valve, maybe something is working out but not all.

[trace automation.shellies_discovery_gen2 2024-12-13T11_49_39.495469+00_00.json](https://github.com/user-attachments/files/18126207/trace.automation.shellies_discovery_gen2.2024-12-13T11_49_39.495469%2B00_00.json)


With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
I tested the Python Script Engine with the hello_world script as sugeested and it works.
Which additional test should I do?
Whats the error in my configuration on the shelly device ?
MQTT is enalbled, the options were set and I also set the server/user/pwd now.
The traces show some information, which coming from the device, so connection is working, I guess.
Any chance for debugging?

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
So the announcment script is running and there is no error, the loop is doing twice, cause I have entered two IDs, the Gateway and the TRV connected to the Gateway.
![image](https://github.com/user-attachments/assets/d7552a61-0696-4ea2-af7c-12eeee149e84)
Is this correct? If its correct, the script engine is working.

The discovery script stops with an error I do not understand:
![image](https://github.com/user-attachments/assets/22d22820-dbd8-44c3-b92d-f8b5bd127c63)

The lines of this script were located in the same file as the lines of the annoncmeent script, how it can be missed?

Is there any script running in the Shelly devices? 
Is it correct, to add the Gateway and the TRV?

I have time today playing around, will see whats happen.

How should I find the TRV in HA, if the scripts working correct? Should I get a device and entities, will I see it as a 'discovered' device? How can I use it with my thermostats? The thermostats (smartThermostst(PID)) working fine.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
When I use the gateway only, same probleems:
When I run only this part of the script I get the erroe 'trigger' undefined.
![image](https://github.com/user-attachments/assets/ff19a4ed-9a25-4c22-8c0d-8e2b801ea34b)

Maybe this is cause I run this lines 'solo', but maybe not.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Thats going on at the Gateway:
![image](https://github.com/user-attachments/assets/e848a501-450e-4bdc-9217-5523607d5bcb)

I only added a TRV but see 3 BT home devices, maybe this were sensors/actors nut the valve as a device.

**Comment by bieniu** [comment]
Devices created by the script will appear as MQTT devices.

Please attach a debug log, without the log I can't help you.

**Comment by bieniu** [comment]
> The discovery script stops with an error I do not understand:

![image](https://github.com/user-attachments/assets/5e6fe486-eaa2-40b7-bf75-e52d77d8e63a)

Shellies Discovery script is not installed.

**Comment by GerhardKreuzer** [comment]
![image](https://github.com/user-attachments/assets/3eeeaa8e-13fc-48c2-9b24-f7e4e053c8e5)
Looks godd?

**Comment by GerhardKreuzer** [comment]
2024-12-14 14:00:53.484 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Error executing script. Service not found for call_service at pos 1: Action python_script.shellies_discovery_gen2 not found
2024-12-14 14:00:53.610 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on shellies_discovery/rpc (qos=0): b'{"id":1,"src":"shellyblugwg3-8cbfeaa8c4b0","dst":"shellies_discovery","result":{"components":[{"key":"ble","config":{"enable":true,"rpc":{"enable":true}}},{"key":"blugw","config":{"sys_led_enable":true}},{"key":"blutrv:200","config":{"id":200,"addr":"28:68:47:fc:d3:d6","name":"BluTrv WNG Schlafzimmer","key":null,"trv":"bthomedevice:200","temp_sensors":[],"dw_sensors":[],"meta":{}}},{"key":"bthome","config":{}},{"key":"bthomedevice:200","config":{"id":200,"addr":"28:68:47:fc:d3:d6","name":"BluTrv WNG Schlafzimmer","key":null,"meta":null},"attrs":{"flags":17,"model_id":8}},{"key":"bthomesensor:200","config":{"id":200,"addr":"28:68:47:fc:d3:d6","name":null,"obj_id":1,"idx":0,"meta":null}},{"key":"bthomesensor:201","config":{"id":201,"addr":"28:68:47:fc:d3:d6","name":null,"obj_id":58,"idx":0,"meta":null}},{"key":"bthomesensor:202","config":{"id":202,"addr":"28:68:47:fc:d3:d6","name":null,"obj_id":69,"idx":0,"meta":null}},{"key":"bthomesensor:203","config":{"id":203,"addr":"28:68:47:fc:d3:d6","name":null,"obj_id":69,"idx":1,"meta":null}},{"key":"cloud","config":{"enable":false,"server":"iot.shelly.cloud:6012/jrpc"}},{"key":"mqtt","config":{"enable":true,"server":"192.168.0.7","client_id":"shellyblugwg3-8cbfeaa8c4b0","user":"\xc3\x84rztezentrum","ssl_ca":null,"topic_prefix":"shellyblugwg3-8cbfeaa8c4b0","rpc_ntf":true,"status_ntf":true,"use_client_cert":false,"enable_rpc":true,"enable_control":true}},{"key":"sys","config":{"device":{"name":"BLU Gateway Gen3 Wohnung","mac":"8CBFEAA8C4B0","fw_id":"20241007-074728/1.4.99-blugwg3prod2-g689f175","discoverable":true,"eco_mode":false},"location":{"tz":null,"lat":null,"lon":null},"debug":{"level":2,"file_level":null,"mqtt":{"enable":true},"websocket":{"enable":true},"file_log":{"enable":false},"udp":{"addr":null}},"ui_data":{},"rpc_udp":{"dst_addr":null,"listen_port":null},"sntp":{"server":"time.cloudflare.com"},"cfg_rev":859}},{"key":"wifi","config":{"ap":{"ssid":"ShellyBluGwG3-8CBFEAA8C4B0","is_open":false, "enable":true, "range_extender": {"enable":true}},"sta":{"ssid":"Wohnung","is_open":false, "enable":true, "ipv4mode":"static","ip":"192.168.0.240","netmask":"255.255.255.0","gw":"192.168.0.1","nameserver":"9.9.9.9"},"sta1":{"ssid":null,"is_open":true, "enable":false, "ipv4mode":"dhcp","ip":null,"netmask":null,"gw":null,"nameserver":null},"roam":{"rssi_thr":-80,"interval":60}}}],"cfg_rev":859,"offset":0,"total":14}}'
2024-12-14 14:00:53.612 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Running automation actions
2024-12-14 14:00:53.613 INFO (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Executing step call service
2024-12-14 14:00:53.614 ERROR (MainThread) [homeassistant.components.automation.shellies_discovery_gen2] Shellies Discovery Gen2: Error executing script. Service not found for call_service at pos 1: Action python_script.shellies_discovery_gen2 not found

No idea how get a file out of HA LogViewer, sorry

**Comment by GerhardKreuzer** [comment]
Scripts not installed?
I can see the scripts in the list, the scrips were running and the scrips were enabled, so whats wrong with the 'script installation'?
![image](https://github.com/user-attachments/assets/45070f4e-ad91-4541-8c4e-7d2b62a776e2)

**Comment by bieniu** [comment]
> I can see the scripts in the list, the scrips were running and the scrips were enabled, so whats wrong with the 'script installation'?

Those are automations, not python_script. You need to check `/config/python_scripts/` folder. There should be `shellies_discovery_gen2.py` file there.

**Comment by GerhardKreuzer** [comment]
ahhh, two things same name ... ok.

**Comment by GerhardKreuzer** [comment]
Ok.
I found the script file in the git repository and copied it into the scrips folder. Now somthing happens, but it needs some time after the restart, which is ok.
![image](https://github.com/user-attachments/assets/aee85cf8-d5f9-4f6f-b340-d22a4d7f53ab)

Attention: I have to run the announce-script manually, so HA do it at startup and I do it manually, after that, the discovery script executes ... this is not that nice if HA do updates and restarts.

Her is what I got:
![image](https://github.com/user-attachments/assets/ce83f652-7019-4129-b681-86aeeff1907a)

No chance to set the valve, but maybe I have to digg deeper ..

With best regards
Gerhard

**Comment by bieniu** [comment]
> I have to run the announce-script manually, so HA do it at startup and I do it manually, after that, the discovery script executes ... this is not that nice if HA do updates and restarts.

It depends on your HA server specifics and performance. You can add a delay to the announcement automation.

> No chance to set the valve, but maybe I have to digg deeper

Look here https://github.com/bieniu/ha-shellies-discovery-gen2/pull/524
