### ISSUE TITLE
Shelly 3EM Pro 400 - Minimum Firmware

### ISSUE THREAD

**Issue by robotsox** [bieniu/ha-shellies-discovery-gen2#541]
Please set the Minimum Firmware of the Shelly 3Em Pro 400 to "ATTR_MIN_FIRMWARE_DATE: 20230119,".
Thank you!

**Comment by bieniu** [comment]
Why?

**Comment by robotsox** [comment]
We have Shellys with Firmware-Version:
`  "fw_id": "20230406-080517/0.14.2-pro3em400prod0-g4fc29d5",
  "ver": "0.14.2-pro3em400prod0",`

so this shellys are not working with tthe minimum firmware:
`ATTR_MIN_FIRMWARE_DATE: 20231219,`

**Comment by bieniu** [comment]
This is very old and outdated firmware, you should update it as soon as possible.
