### ISSUE TITLE
NameError: name 'data' is not defined, line 4174

### ISSUE THREAD

**Issue by sirtakahe** [bieniu/ha-shellies-discovery-gen2#544]
**Describe the bug**

HA logs show this error on boot up when running the shelly script:

This error originated from a custom integration.

Logger: custom_components.pyscript.file.shellies_discovery_gen2
Source: custom_components/pyscript/global_ctx.py:341
integration: Pyscript Python scripting (documentation, issues)
First occurred: 4:46:54 PM (3 occurrences)
Last logged: 4:47:05 PM

Exception in </config/pyscript/shellies_discovery_gen2.py> line 4174: device_id = data[ATTR_ID] # noqa: F821 ^ NameError: name 'data' is not defined

**Versions:**
 - Home Assistant: 
Core 2024.12.5
Supervisor 2024.12.0
Operating System 14.1
Frontend 20241127.8

**Comment by bieniu** [comment]
This script is designed for pythons_script component not for pyscript.
