### ISSUE TITLE
Add support for Shelly Pro 3EM-3CT6

### ISSUE THREAD

**Issue by EarlSneedSinclair** [bieniu/ha-shellies-discovery-gen2#545]
Hello,

First, thank you for the incredible work you’ve put into this project. It’s truly appreciated!

I would like to kindly request the addition of support for the Shelly Pro 3EM-3CT6 device. I have attached the RPC responses to GetConfig and GetStatus to assist with this request.

[Shelly Pro 3EM-3CT6  - Shelly.GetStatus.json](https://github.com/user-attachments/files/18259205/Shelly.Pro.3EM-3CT6.-.Shelly.GetStatus.json)
[Shelly Pro 3EM-3CT6 - Shelly.GetConfig.json](https://github.com/user-attachments/files/18259206/Shelly.Pro.3EM-3CT6.-.Shelly.GetConfig.json)

**Comment by bieniu** [comment]
Does the `id` in the response to `http://<DEVICE_IP>/shelly` look like this `ShellyPro3EM3CT63-XXXXXXXX`?

**Comment by EarlSneedSinclair** [comment]
Yes it does. It includes the MAC address.

```
id: "shellypro3em63-[MAC address]"
```

**Comment by EarlSneedSinclair** [comment]
That was quick. I can confirm it's working as expected.

Many thanks, and I wish you a Happy New Year!

**Comment by bieniu** [comment]
Happy New Year 🎉
