### ISSUE TITLE
Point "Visit device" URL to IP instead of hostname

### ISSUE THREAD

**Issue by davidw3591** [bieniu/ha-shellies-discovery-gen2#71]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In HomeAssistant the "Visit device" URL in the device configuration page is pointing to _device-id.local_ instead if the IP-address like with the Gen1's.
E.g.: _http://shellypro2-30c6f784b9b8.local/_

This doesn't work in my network: DNS_PROBE_FINISHED_NXDOMAIN
Is it possible to use the IP address instead?

**Additional context**
![Schermafbeelding 2022-06-25 124136](https://user-images.githubusercontent.com/22191954/175770142-72cbed89-4b76-4f11-9a74-e8eba5e9ad37.jpg)
Have it automatically choose the IP of the interface that does not have a "None" address?

**Comment by bieniu** [comment]
Duplicate #9
