### ISSUE TITLE
As a user, I'd like to upload JS script via MQTT.

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [bieniu/ha-shellies-discovery-gen2#78]
**Is your feature request related to a problem? Please describe.**

As a part os 1.2.0 release, device-side JS code was intoduced, creating a breaking change for user of current automation.
Shelly device can located in a distant location which user visits once in a while.
Moving with architectural implementations (implementing JS code device-side) requires user to gain HTTP connectivity at a distant location to update Shelly configuration.

**Describe the solution you'd like**

It would be great to inject JS script into Shelly via MQTT.  
Looks like Shelly Gen2 API is transport-agnostic and you can acheive identical things via HTTP and MQTT:
* https://shelly-api-docs.shelly.cloud/gen2/General/RPCChannels/
* https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Script

Idea can be improved and maybe `ha-shellies-discovery-gen2` will inject JS script by itself?

**Comment by roopesh** [comment]
I'm curious, @bieniu , why the decision was made to split the logic between device-side and server-side scripts.  Seems to me less maintenance would be better.  There's (potentially) a lot of devices to update if the script ever had to change, and a slightly higher learning curve for adoption.

**Comment by bieniu** [comment]
@roopesh IMO pushing data is a better solution than polling, this reduces the amount of messages sent to the broker and shifts them over time. Ideally, HA integration would only be based on what it will get from the device without having to poll it. Unfortunately, Shelly developers do not want devices to periodically send this data by themselves and advise to write scripts. A similar problem concerns the state of relays without power measuring and inputs.
