### ISSUE TITLE
shellies_discovery_gen2 Not triggering

### ISSUE THREAD

**Issue by sgstokes** [bieniu/ha-shellies-discovery-gen2#86]
**Describe the bug**
I followed the setup, and restarted twice, but the `shellies_discovery_gen2` trigger topic `shellies_discovery/rpc` is not present.  See attached screenshot.

**Expected behavior**
`shellies_discovery_gen2` automation should trigger and execute `python_script.shellies_discovery_gen2`.

**Versions:**
 - Home Assistant 2022.8.2
   - Supervisor 2022.07.0
   - Operating System 8.4
   - Frontend 20220802.0 - latest
 - Shellies Discovery GEN2: 1.4.0
 - Shelly device firmware: 20220211-132652/plugusprod2_app-gcb4621f

**Shellies Discovery GEN2 automation:**
```
- id: shellies_announce_gen2
  alias: "Shellies Announce Gen2"
  trigger:
    - platform: homeassistant
      event: start
  variables:
    device_info_payload: "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
    device_ids: # enter the list of device IDs here
      - shellyplugus-083af201a57c
  action:
    - repeat:
        for_each: "{{ device_ids }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: "{{ repeat.item }}/rpc"
              payload: "{{ device_info_payload }}"

- id: shellies_discovery_gen2
  alias: "Shellies Discovery Gen2"
  mode: queued
  max: 999
  trigger:
    - platform: mqtt
      topic: shellies_discovery/rpc
  action:
    - service: python_script.shellies_discovery_gen2
      data:
        id: "{{ trigger.payload_json.src }}"
        device_config: "{{ trigger.payload_json.result }}"
```

**Debug log:**
```
2022-08-09 10:16:00.385 DEBUG (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Automation triggered
2022-08-09 10:16:00.400 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Running automation actions
2022-08-09 10:16:00.401 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeating sequence: Iteration 1 of 1 with item: 'shellyplugus-083af201a57c'
2022-08-09 10:16:00.405 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Running automation actions
2022-08-09 10:16:00.405 INFO (MainThread) [homeassistant.components.automation.shellies_announce_gen2] Shellies Announce Gen2: Repeat at step 1: Executing step call service
```
<img width="1136" alt="Screen Shot 2022-08-09 at 10 22 26" src="https://user-images.githubusercontent.com/30154728/183675551-9fcb397d-0fd1-422d-bc78-0c8a87f7961c.png">

**Comment by bieniu** [comment]
Please enable `debug` for `python_script` integration https://github.com/bieniu/ha-shellies-discovery-gen2#how-to-debug

**Comment by sgstokes** [comment]
It is enabled, along with `homeassistant.components.automation`.  I set them both to `debug`.

**Comment by bieniu** [comment]
`shellies_discovery/rpc` topic should be sent by device, not script/automation. Have you set up MQTT on the device correctly? There are no topics from the device `shellyplugus-083af201a57c` on the screenshot.

**Comment by sgstokes** [comment]
See screenshots. `shellyplugus-LRLamp2` is the device with ID: `shellyplugus-083af201a57c`.

<img width="1209" alt="Screen Shot 2022-08-09 at 12 27 16" src="https://user-images.githubusercontent.com/30154728/183706480-d36450f7-8512-4094-8e52-d7458a7f9648.png">
<img width="1257" alt="Screen Shot 2022-08-09 at 12 28 10" src="https://user-images.githubusercontent.com/30154728/183706608-4292d456-ce63-4fe7-b4aa-10d41b557f8b.png">

**Comment by sgstokes** [comment]
I updated the MQPrefix and that resolved the issue.

**Comment by bieniu** [comment]
If you changed the device ID to shellyplugus-LRLamp2 you must use that ID in your announce automation.

**Comment by sgstokes** [comment]
Thank you!
