### ISSUE TITLE
Wrong device redirection address

### ISSUE THREAD

**Issue by lukcz** [bieniu/ha-shellies-discovery-gen2#9]
Not sure whether it is related to Your script or is it HA related issue, but clicking 'Visit device' results in wrong address being passed to the browser - it should be device IP but is "device-name.local". Hitting "Visit device" should redirect me to the correct device webpage.

Also maybe I should mention that I have a custom device name being set in the shelly firmware.

![image](https://user-images.githubusercontent.com/6866304/151414950-9a440de9-61cb-4c37-9748-535506b6f64d.png)

**Comment by bieniu** [comment]
This button opens `<device_id>.local` url and this is the correct webpage.

**Comment by bieniu** [comment]
Do you need more information or can we close this issue?

**Comment by lukcz** [comment]
To be honest, it didn't help me. The url that is being opened leads to webpage that does not exist. I assume it is due to the fact that there is no information available how the webpage address <device.id>.local should be translated to correct IP address. In my case webpage address is http://shellyplus1pm-xxxxxxxxxxxx.local/ .In gen1 Shellies the address was always the IP of the device and there was no need to resolve it, it just worked.

**Comment by lukcz** [comment]
Seems like my router does not support mDNS, so I guess You can close this issue. Anyway, thanks for the help!

**Comment by bieniu** [comment]
I asked Shelly team to add IP address to `Shelly.GetConfig` payload, with this the script will have the device IP during configuration. So there is a hope... ;)
